/**
 * Generate src/lib/__tests__/fixtures/coverageMerchants.json from the production
 * Supabase database.
 *
 * Usage:
 *   1. Ensure SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY are set in env (vercel env pull or .env.local)
 *   2. npx tsx scripts/generateCoverageFixture.ts
 *
 * The output is committed to source — that's intentional. The fixture is a
 * deterministic snapshot of production at fixture-generation time. Regenerate
 * after meaningful coverage changes (new rules, new merchants seen).
 */

import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { DEFAULT_HOUSEHOLD_ID } from '@/lib/constants'

const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in env')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

interface Row {
  merchant: string | null
  amount: number
}

async function main() {
  // Pull all CSV transactions in chunks (Supabase default page size = 1000)
  const all: Row[] = []
  let from = 0
  const pageSize = 1000
  while (true) {
    const { data, error } = await supabase
      .from('transactions')
      .select('merchant, amount')
      .eq('household_id', DEFAULT_HOUSEHOLD_ID)
      .eq('source', 'csv')
      .eq('is_transfer', false)
      .not('merchant', 'is', null)
      .range(from, from + pageSize - 1)
    if (error) throw error
    if (!data || data.length === 0) break
    all.push(...(data as Row[]))
    if (data.length < pageSize) break
    from += pageSize
  }

  console.log(`Fetched ${all.length} transactions`)

  // Group by merchant
  const groups = new Map<string, { isIncome: boolean; count: number; totalAmount: number }>()
  for (const row of all) {
    const m = row.merchant
    if (!m) continue
    const existing = groups.get(m) ?? { isIncome: false, count: 0, totalAmount: 0 }
    existing.isIncome = existing.isIncome || row.amount > 0
    existing.count += 1
    existing.totalAmount += Math.abs(row.amount)
    groups.set(m, existing)
  }

  const merchants = Array.from(groups.entries())
    .map(([merchant, g]) => ({
      merchant,
      isIncome: g.isIncome,
      count: g.count,
      totalAmount: Math.round(g.totalAmount * 100) / 100,
    }))
    .sort((a, b) => b.totalAmount - a.totalAmount)

  const fixture = {
    _meta: {
      generated: new Date().toISOString().slice(0, 10),
      source: 'Generated by scripts/generateCoverageFixture.ts',
      regenerate: 'Run scripts/generateCoverageFixture.ts',
    },
    merchants,
  }

  const outPath = resolve(__dirname, '../src/lib/__tests__/fixtures/coverageMerchants.json')
  writeFileSync(outPath, JSON.stringify(fixture, null, 2) + '\n')
  console.log(`Wrote ${merchants.length} unique merchants to ${outPath}`)
}

main().catch(e => {
  console.error(e)
  process.exit(1)
})
